name: XCore
version: '1.0-SNAPSHOT'
main: de.ruben.xcore.XCore
api-version: 1.16
depend: [XDevApi, PlaceholderAPI, HolographicDisplays]
authors: [ Ruben ]
commands:
  cash:
    aliases: [money]
  pay:
  eco:
  bank:
  adminprofile:
    aliases: [aprofile]
  getstorage:
  storageUpgradeItem:
  testench:
  changelog:
  createchangelog:
  editchangelog:
  adminenchant:
    aliases: [ae]
  aktien:
  job:
  nextevent:
  admintutorial:
    aliases: [at]
  tutorialcenter:
    aliases: [ tutc ]
  clan:
  admingamble:
  gamble:
